[2025-10-20T18:43:51.702+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-20T18:43:51.724+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_to_snowflake.deleteXcom scheduled__2025-10-20T17:30:00+00:00 [queued]>
[2025-10-20T18:43:51.730+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_to_snowflake.deleteXcom scheduled__2025-10-20T17:30:00+00:00 [queued]>
[2025-10-20T18:43:51.730+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-20T18:43:51.738+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): deleteXcom> on 2025-10-20 17:30:00+00:00
[2025-10-20T18:43:51.744+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_to_snowflake', 'deleteXcom', 'scheduled__2025-10-20T17:30:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/minio_to_snowflake.py', '--cfg-path', '/tmp/tmpz_futh6b']
[2025-10-20T18:43:51.746+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask deleteXcom
[2025-10-20T18:43:51.745+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=15074) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-20T18:43:51.748+0000] {standard_task_runner.py:64} INFO - Started process 15084 to run task
[2025-10-20T18:43:51.784+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_to_snowflake.deleteXcom scheduled__2025-10-20T17:30:00+00:00 [running]> on host 247b7821f06b
[2025-10-20T18:43:51.847+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_to_snowflake' AIRFLOW_CTX_TASK_ID='deleteXcom' AIRFLOW_CTX_EXECUTION_DATE='2025-10-20T17:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-20T17:30:00+00:00'
[2025-10-20T18:43:51.847+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-20T18:43:51.857+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-20T18:43:51.858+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/minio_to_snowflake.py", line 72, in cleanup_task1_xcom
    XCom.clear(dag_id=dag_id, task_id=task_id_to_clear)
    ^^^^
NameError: name 'XCom' is not defined
[2025-10-20T18:43:51.867+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=minio_to_snowflake, task_id=deleteXcom, run_id=scheduled__2025-10-20T17:30:00+00:00, execution_date=20251020T173000, start_date=20251020T184351, end_date=20251020T184351
[2025-10-20T18:43:51.875+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 29 for task deleteXcom (name 'XCom' is not defined; 15084)
[2025-10-20T18:43:51.889+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-20T18:43:51.902+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-20T18:43:51.903+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
