[2025-10-20T18:52:19.156+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-20T18:52:19.178+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_to_snowflake.deleteXcom manual__2025-10-20T17:36:04.068862+00:00 [queued]>
[2025-10-20T18:52:19.183+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_to_snowflake.deleteXcom manual__2025-10-20T17:36:04.068862+00:00 [queued]>
[2025-10-20T18:52:19.184+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-20T18:52:19.192+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): deleteXcom> on 2025-10-20 17:36:04.068862+00:00
[2025-10-20T18:52:19.198+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_to_snowflake', 'deleteXcom', 'manual__2025-10-20T17:36:04.068862+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/minio_to_snowflake.py', '--cfg-path', '/tmp/tmp0twmb_sj']
[2025-10-20T18:52:19.200+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask deleteXcom
[2025-10-20T18:52:19.200+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=20180) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-20T18:52:19.202+0000] {standard_task_runner.py:64} INFO - Started process 20190 to run task
[2025-10-20T18:52:19.236+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_to_snowflake.deleteXcom manual__2025-10-20T17:36:04.068862+00:00 [running]> on host 247b7821f06b
[2025-10-20T18:52:19.297+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_to_snowflake' AIRFLOW_CTX_TASK_ID='deleteXcom' AIRFLOW_CTX_EXECUTION_DATE='2025-10-20T17:36:04.068862+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-20T17:36:04.068862+00:00'
[2025-10-20T18:52:19.298+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-20T18:52:19.308+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-20T18:52:19.308+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/minio_to_snowflake.py", line 72, in cleanup_task1_xcom
    XCom.clear(dag_id=dag_id, task_id=task_id_to_clear)
    ^^^^
NameError: name 'XCom' is not defined
[2025-10-20T18:52:19.318+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=minio_to_snowflake, task_id=deleteXcom, run_id=manual__2025-10-20T17:36:04.068862+00:00, execution_date=20251020T173604, start_date=20251020T185219, end_date=20251020T185219
[2025-10-20T18:52:19.324+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 34 for task deleteXcom (name 'XCom' is not defined; 20190)
[2025-10-20T18:52:19.344+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-20T18:52:19.357+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-20T18:52:19.358+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
