[2025-10-20T18:52:22.347+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-20T18:52:22.369+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_to_snowflake.deleteXcom scheduled__2025-10-20T18:30:00+00:00 [queued]>
[2025-10-20T18:52:22.375+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_to_snowflake.deleteXcom scheduled__2025-10-20T18:30:00+00:00 [queued]>
[2025-10-20T18:52:22.375+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-20T18:52:22.383+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): deleteXcom> on 2025-10-20 18:30:00+00:00
[2025-10-20T18:52:22.389+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_to_snowflake', 'deleteXcom', 'scheduled__2025-10-20T18:30:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/minio_to_snowflake.py', '--cfg-path', '/tmp/tmps4kv98zb']
[2025-10-20T18:52:22.392+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask deleteXcom
[2025-10-20T18:52:22.391+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=20191) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-20T18:52:22.394+0000] {standard_task_runner.py:64} INFO - Started process 20201 to run task
[2025-10-20T18:52:22.430+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_to_snowflake.deleteXcom scheduled__2025-10-20T18:30:00+00:00 [running]> on host 247b7821f06b
[2025-10-20T18:52:22.493+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_to_snowflake' AIRFLOW_CTX_TASK_ID='deleteXcom' AIRFLOW_CTX_EXECUTION_DATE='2025-10-20T18:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-20T18:30:00+00:00'
[2025-10-20T18:52:22.494+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-20T18:52:22.504+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-20T18:52:22.504+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/minio_to_snowflake.py", line 72, in cleanup_task1_xcom
    XCom.clear(dag_id=dag_id, task_id=task_id_to_clear)
    ^^^^
NameError: name 'XCom' is not defined
[2025-10-20T18:52:22.514+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=minio_to_snowflake, task_id=deleteXcom, run_id=scheduled__2025-10-20T18:30:00+00:00, execution_date=20251020T183000, start_date=20251020T185222, end_date=20251020T185222
[2025-10-20T18:52:22.520+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 35 for task deleteXcom (name 'XCom' is not defined; 20201)
[2025-10-20T18:52:22.537+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-20T18:52:22.551+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-20T18:52:22.552+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
